//###########################################################################
//
// FILE:   can_message.h
//
// TITLE:  Auto-generated CAN message definitions from DBC
//
// GENERATED BY: tools/dbc_to_c.py
// SOURCE DBC:   ecu_example.dbc
//
// WARNING: This file is auto-generated. Do not edit manually.
//          Re-run the generator when the DBC file changes.
//
//###########################################################################

#ifndef CAN_MESSAGE_H_
#define CAN_MESSAGE_H_

#include <stdint.h>

//
// CAN Message IDs
//
#define CAN_ID_ENGINE_DATA                       (0x100U)
#define CAN_ID_TRANSMISSION_DATA                 (0x200U)
#define CAN_ID_VEHICLE_STATUS                    (0x300U)
#define CAN_ID_TESTER_COMMAND                    (0x400U)

//
// CAN Message DLCs (bytes)
//
#define CAN_DLC_ENGINE_DATA                      (8U)
#define CAN_DLC_TRANSMISSION_DATA                (8U)
#define CAN_DLC_VEHICLE_STATUS                   (8U)
#define CAN_DLC_TESTER_COMMAND                   (8U)

//
// CAN Message Cycle Times (ms, 0 = event-triggered)
//
#define CAN_CYCLE_ENGINE_DATA                    (100U)
#define CAN_CYCLE_TRANSMISSION_DATA              (200U)
#define CAN_CYCLE_VEHICLE_STATUS                 (50U)
#define CAN_CYCLE_TESTER_COMMAND                 (0U)

//
// Number of TX messages (sent by ECU)
//
#define CAN_NUM_TX_MSGS  (3U)

//
// Number of RX messages (received by ECU)
//
#define CAN_NUM_RX_MSGS  (1U)

// Engine data broadcast by ECU at 100ms
typedef struct
{
    uint16_t     EngineSpeed;  // Engine speed in RPM
    uint8_t      EngineTemp;  // Engine coolant temperature
    uint8_t      ThrottlePos;  // Throttle pedal position percentage
    uint8_t      EngineStatus;  // 0=Off, 1=Cranking, 2=Running, 3=Error
} CAN_MSG_ENGINE_DATA_t;

// Transmission data broadcast by ECU at 200ms
typedef struct
{
    uint8_t      GearPosition;
    uint8_t      TransTemp;
    uint8_t      TransStatus;
} CAN_MSG_TRANSMISSION_DATA_t;

// Vehicle status broadcast by ECU at 50ms
typedef struct
{
    uint16_t     VehicleSpeed;  // Vehicle speed from wheel sensors
    uint8_t      BrakePressure;
    uint16_t     SteeringAngle;
} CAN_MSG_VEHICLE_STATUS_t;

// Command message sent from Tester to ECU
typedef struct
{
    uint8_t      CommandType;  // Command type identifier
    uint32_t     CommandData;
    uint8_t      CommandCounter;
} CAN_MSG_TESTER_COMMAND_t;

//
// Pack functions: struct -> raw CAN data bytes
//
void CAN_Pack_EngineData(uint16_t data[], const CAN_MSG_ENGINE_DATA_t *msg);
void CAN_Pack_TransmissionData(uint16_t data[], const CAN_MSG_TRANSMISSION_DATA_t *msg);
void CAN_Pack_VehicleStatus(uint16_t data[], const CAN_MSG_VEHICLE_STATUS_t *msg);
void CAN_Pack_TesterCommand(uint16_t data[], const CAN_MSG_TESTER_COMMAND_t *msg);

//
// Unpack functions: raw CAN data bytes -> struct
//
void CAN_Unpack_EngineData(CAN_MSG_ENGINE_DATA_t *msg, const uint16_t data[]);
void CAN_Unpack_TransmissionData(CAN_MSG_TRANSMISSION_DATA_t *msg, const uint16_t data[]);
void CAN_Unpack_VehicleStatus(CAN_MSG_VEHICLE_STATUS_t *msg, const uint16_t data[]);
void CAN_Unpack_TesterCommand(CAN_MSG_TESTER_COMMAND_t *msg, const uint16_t data[]);

#endif // CAN_MESSAGE_H_
