//###########################################################################
//
// FILE:   can_message.c
//
// TITLE:  Auto-generated CAN message definitions from DBC
//
// GENERATED BY: tools/dbc_to_c.py
// SOURCE DBC:   ecu_example.dbc
//
// WARNING: This file is auto-generated. Do not edit manually.
//          Re-run the generator when the DBC file changes.
//
//###########################################################################

//
// Included Files
//
#include "can_message.h"

//
// Pack EngineData (0x100) signals into raw data array
//
void CAN_Pack_EngineData(uint16_t data[], const CAN_MSG_ENGINE_DATA_t *msg)
{
    uint16_t i;
    for (i = 0; i < 8U; i++)
    {
        data[i] = 0U;
    }
    // EngineSpeed: start=0, len=16
    data[0] |= ((uint16_t)msg->EngineSpeed & 0xFFU) << 0U;
    data[1] |= (((uint16_t)msg->EngineSpeed >> 8U) & 0xFFU) << 0U;
    // EngineTemp: start=16, len=8
    data[2] |= ((uint16_t)msg->EngineTemp & 0xFFU) << 0U;
    // ThrottlePos: start=24, len=8
    data[3] |= ((uint16_t)msg->ThrottlePos & 0xFFU) << 0U;
    // EngineStatus: start=32, len=2
    data[4] |= ((uint16_t)msg->EngineStatus & 0x03U) << 0U;
}

//
// Unpack EngineData (0x100) raw data into signal struct
//
void CAN_Unpack_EngineData(CAN_MSG_ENGINE_DATA_t *msg, const uint16_t data[])
{
    // EngineSpeed: start=0, len=16
    msg->EngineSpeed = 0;
    msg->EngineSpeed |= ((uint16_t)(data[0] >> 0U) & 0xFFU);
    msg->EngineSpeed |= (((uint16_t)(data[1] >> 0U) & 0xFFU) << 8U);
    // EngineTemp: start=16, len=8
    msg->EngineTemp = 0;
    msg->EngineTemp |= ((uint8_t)(data[2] >> 0U) & 0xFFU);
    // ThrottlePos: start=24, len=8
    msg->ThrottlePos = 0;
    msg->ThrottlePos |= ((uint8_t)(data[3] >> 0U) & 0xFFU);
    // EngineStatus: start=32, len=2
    msg->EngineStatus = 0;
    msg->EngineStatus |= ((uint8_t)(data[4] >> 0U) & 0x03U);
}

//
// Pack TransmissionData (0x200) signals into raw data array
//
void CAN_Pack_TransmissionData(uint16_t data[], const CAN_MSG_TRANSMISSION_DATA_t *msg)
{
    uint16_t i;
    for (i = 0; i < 8U; i++)
    {
        data[i] = 0U;
    }
    // GearPosition: start=0, len=4
    data[0] |= ((uint16_t)msg->GearPosition & 0x0FU) << 0U;
    // TransTemp: start=8, len=8
    data[1] |= ((uint16_t)msg->TransTemp & 0xFFU) << 0U;
    // TransStatus: start=16, len=2
    data[2] |= ((uint16_t)msg->TransStatus & 0x03U) << 0U;
}

//
// Unpack TransmissionData (0x200) raw data into signal struct
//
void CAN_Unpack_TransmissionData(CAN_MSG_TRANSMISSION_DATA_t *msg, const uint16_t data[])
{
    // GearPosition: start=0, len=4
    msg->GearPosition = 0;
    msg->GearPosition |= ((uint8_t)(data[0] >> 0U) & 0x0FU);
    // TransTemp: start=8, len=8
    msg->TransTemp = 0;
    msg->TransTemp |= ((uint8_t)(data[1] >> 0U) & 0xFFU);
    // TransStatus: start=16, len=2
    msg->TransStatus = 0;
    msg->TransStatus |= ((uint8_t)(data[2] >> 0U) & 0x03U);
}

//
// Pack VehicleStatus (0x300) signals into raw data array
//
void CAN_Pack_VehicleStatus(uint16_t data[], const CAN_MSG_VEHICLE_STATUS_t *msg)
{
    uint16_t i;
    for (i = 0; i < 8U; i++)
    {
        data[i] = 0U;
    }
    // VehicleSpeed: start=0, len=16
    data[0] |= ((uint16_t)msg->VehicleSpeed & 0xFFU) << 0U;
    data[1] |= (((uint16_t)msg->VehicleSpeed >> 8U) & 0xFFU) << 0U;
    // BrakePressure: start=16, len=8
    data[2] |= ((uint16_t)msg->BrakePressure & 0xFFU) << 0U;
    // SteeringAngle: start=24, len=16
    data[3] |= ((uint16_t)msg->SteeringAngle & 0xFFU) << 0U;
    data[4] |= (((uint16_t)msg->SteeringAngle >> 8U) & 0xFFU) << 0U;
}

//
// Unpack VehicleStatus (0x300) raw data into signal struct
//
void CAN_Unpack_VehicleStatus(CAN_MSG_VEHICLE_STATUS_t *msg, const uint16_t data[])
{
    // VehicleSpeed: start=0, len=16
    msg->VehicleSpeed = 0;
    msg->VehicleSpeed |= ((uint16_t)(data[0] >> 0U) & 0xFFU);
    msg->VehicleSpeed |= (((uint16_t)(data[1] >> 0U) & 0xFFU) << 8U);
    // BrakePressure: start=16, len=8
    msg->BrakePressure = 0;
    msg->BrakePressure |= ((uint8_t)(data[2] >> 0U) & 0xFFU);
    // SteeringAngle: start=24, len=16
    msg->SteeringAngle = 0;
    msg->SteeringAngle |= ((uint16_t)(data[3] >> 0U) & 0xFFU);
    msg->SteeringAngle |= (((uint16_t)(data[4] >> 0U) & 0xFFU) << 8U);
}

//
// Pack TesterCommand (0x400) signals into raw data array
//
void CAN_Pack_TesterCommand(uint16_t data[], const CAN_MSG_TESTER_COMMAND_t *msg)
{
    uint16_t i;
    for (i = 0; i < 8U; i++)
    {
        data[i] = 0U;
    }
    // CommandType: start=0, len=8
    data[0] |= ((uint16_t)msg->CommandType & 0xFFU) << 0U;
    // CommandData: start=8, len=32
    data[1] |= ((uint16_t)msg->CommandData & 0xFFU) << 0U;
    data[2] |= (((uint16_t)msg->CommandData >> 8U) & 0xFFU) << 0U;
    data[3] |= (((uint16_t)msg->CommandData >> 16U) & 0xFFU) << 0U;
    data[4] |= (((uint16_t)msg->CommandData >> 24U) & 0xFFU) << 0U;
    // CommandCounter: start=40, len=8
    data[5] |= ((uint16_t)msg->CommandCounter & 0xFFU) << 0U;
}

//
// Unpack TesterCommand (0x400) raw data into signal struct
//
void CAN_Unpack_TesterCommand(CAN_MSG_TESTER_COMMAND_t *msg, const uint16_t data[])
{
    // CommandType: start=0, len=8
    msg->CommandType = 0;
    msg->CommandType |= ((uint8_t)(data[0] >> 0U) & 0xFFU);
    // CommandData: start=8, len=32
    msg->CommandData = 0;
    msg->CommandData |= ((uint32_t)(data[1] >> 0U) & 0xFFU);
    msg->CommandData |= (((uint32_t)(data[2] >> 0U) & 0xFFU) << 8U);
    msg->CommandData |= (((uint32_t)(data[3] >> 0U) & 0xFFU) << 16U);
    msg->CommandData |= (((uint32_t)(data[4] >> 0U) & 0xFFU) << 24U);
    // CommandCounter: start=40, len=8
    msg->CommandCounter = 0;
    msg->CommandCounter |= ((uint8_t)(data[5] >> 0U) & 0xFFU);
}

//
// End of File
//
